### ISSUE TITLE
Will h265 be supported?

### ISSUE THREAD

**Issue by DanijelBojcic** [alexeyvasilyev/rtsp-client-android#13]
Are there some limitations that doesn't allow h265 to be supported, if not I'm wondering how hard would it be to do?

I would like to help you with this because this is the best RTSP player so far I've found.

**Comment by alexeyvasilyev** [comment]
H265 stream uses different NAL units. Some modifications needed.
H265 support is in TODO list.

**Comment by alexeyvasilyev** [comment]
Done. Check version 5.0.0.
