### ISSUE TITLE
how to get current frame.

### ISSUE THREAD

**Issue by janeSmith99221** [alexeyvasilyev/rtsp-client-android#17]
I'm trying to get current frame during streaming. is there any way to get current frame.

**Comment by alexeyvasilyev** [comment]
Use this code to get any bitmap from SurfaceView:
```
    fun getSnapshot(): Bitmap? {
        val surfaceBitmap = Bitmap.createBitmap(800, 600, Bitmap.Config.ARGB_8888)
        val lock = Object()
        val success = AtomicBoolean(false)
        val thread = HandlerThread("PixelCopyHelper")
        thread.start()
        val sHandler = Handler(thread.looper)
        val listener = PixelCopy.OnPixelCopyFinishedListener { copyResult ->
            success.set(copyResult == PixelCopy.SUCCESS)
            synchronized (lock) {
                lock.notify()
            }
        }
        synchronized (lock) {
            PixelCopy.request(holder.surface, surfaceBitmap, listener, sHandler)
            lock.wait()
        }
        thread.quitSafely()
        return if (success.get()) surfaceBitmap else null
    }

```

**Comment by janeSmith99221** [comment]
thanks for quick reply.

**Comment by janeSmith99221** [comment]
> Use this code to get any bitmap from SurfaceView:
> 
> ```
>     fun getSnapshot(): Bitmap? {
>         val surfaceBitmap = Bitmap.createBitmap(800, 600, Bitmap.Config.ARGB_8888)
>         val lock = Object()
>         val success = AtomicBoolean(false)
>         val thread = HandlerThread("PixelCopyHelper")
>         thread.start()
>         val sHandler = Handler(thread.looper)
>         val listener = PixelCopy.OnPixelCopyFinishedListener { copyResult ->
>             success.set(copyResult == PixelCopy.SUCCESS)
>             synchronized (lock) {
>                 lock.notify()
>             }
>         }
>         synchronized (lock) {
>             PixelCopy.request(holder.surface, surfaceBitmap, listener, sHandler)
>             lock.wait()
>         }
>         thread.quitSafely()
>         return if (success.get()) surfaceBitmap else null
>     }
> ```
getting this exception
Only the original thread that created a view hierarchy can touch its views.
how I can resolve this.
