### ISSUE TITLE
getting exception: Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by janeSmith99221** [alexeyvasilyev/rtsp-client-android#18]
I tried to get frame from received stream using your reference to get bitmap.

  fun getSnapshot(): Bitmap? {
        val surfaceBitmap = Bitmap.createBitmap(800, 600, Bitmap.Config.ARGB_8888)
        val lock = Object()
        val success = AtomicBoolean(false)
        val thread = HandlerThread("PixelCopyHelper")
        thread.start()
        val sHandler = Handler(thread.looper)
        val listener = PixelCopy.OnPixelCopyFinishedListener { copyResult ->
            success.set(copyResult == PixelCopy.SUCCESS)
            synchronized (lock) {
                lock.notify()
            }
        }
        synchronized (lock) {
            PixelCopy.request(holder.surface, surfaceBitmap, listener, sHandler)
            lock.wait()
        }
        thread.quitSafely()
        return if (success.get()) surfaceBitmap else null
    }

but getting Only the original thread that created a view hierarchy can touch its views. this exception

**Comment by alexeyvasilyev** [comment]
See https://github.com/alexeyvasilyev/rtsp-client-android/commit/04c8caaf9144b115e57baadf7b1826ed62597e17
