### ISSUE TITLE
how to get frames without preview.

### ISSUE THREAD

**Issue by janeSmith99221** [alexeyvasilyev/rtsp-client-android#24]
I want to capture frames without preview. is there any way to do this.

**Comment by alexeyvasilyev** [comment]
See https://github.com/alexeyvasilyev/rtsp-client-android/blob/master/README.md
You need to use RtspClient.Builder

**Comment by janeSmith99221** [comment]
> See https://github.com/alexeyvasilyev/rtsp-client-android/blob/master/README.md You need to use RtspClient.Builder

can't understand. can you explain how I can get frames through  RtspClient.Builder.
