### ISSUE TITLE
Exception of getInputBuffer not caught

### ISSUE THREAD

**Issue by Fruchtzwerg94** [alexeyvasilyev/rtsp-client-android#27]
I've noticed a potential crash due to a not caught exception in

https://github.com/alexeyvasilyev/rtsp-client-android/blob/89dfb21c8bd5199eac8e89762b05640cd25df0a3/library-client-rtsp/src/main/java/com/alexvas/rtsp/codec/VideoDecodeThread.kt#L62

[public ByteBuffer getInputBuffer (int index)](https://developer.android.com/reference/android/media/MediaCodec#getInputBuffer(int)) could throw a [MediaCodec.CodecException](https://developer.android.com/reference/android/media/MediaCodec.CodecException) which is currently uncaught.

I've added a handler in #28
I hope I've missed nothing here.

**Comment by alexeyvasilyev** [comment]
Implemented in 2.0.3.
