### ISSUE TITLE
decode h264/h265 frames to bitmap without using surface

### ISSUE THREAD

**Issue by sam21abc** [alexeyvasilyev/rtsp-client-android#32]
Surface is used for decoding raw H264.
```
 val decoder = MediaCodec.createDecoderByType(mimeType)
        val format = MediaFormat.createVideoFormat(mimeType, width, height)

        decoder.configure(format, surface, null, 0)
        decoder.start()
```
is there any other way to get bitmap from decoded frames without surface.

**Comment by Lucaszw** [comment]
+1 Regarding this!

**Comment by rmcamps** [comment]
Did you get how to get bitmap from decoded frames?

**Comment by DalalAlmotwaa** [comment]
+1 Regarding this

**Comment by alexeyvasilyev** [comment]
Use https://github.com/alexeyvasilyev/rtsp-client-android/blob/master/library-client-rtsp/src/main/java/com/alexvas/rtsp/widget/RtspImageView.kt
