### ISSUE TITLE
Aspect ratio.

### ISSUE THREAD

**Issue by janeSmith99221** [alexeyvasilyev/rtsp-client-android#40]
how to change surfaceview aspect ratio.
it  possible to change aspect ratio through xml:  app:layout_constraintDimensionRatio="4:3". but want to change programmatically.
is there any way.

**Comment by alexeyvasilyev** [comment]
Take a look at https://github.com/androidx/media/blob/release/libraries/ui/src/main/java/androidx/media3/ui/AspectRatioFrameLayout.java
