### ISSUE TITLE
Can not stream with rtsp url: "rtsp://192.168.1.1:8080/mjpeg/1

### ISSUE THREAD

**Issue by quockhanh1198** [alexeyvasilyev/rtsp-client-android#5]
Hi Alexey, I already run this app with my above url, I changed RTSP username and RTSP password with my access point, I use ESP32-Cam and I set it an access point. However I can not stream on android. I don't know the reason about this issue. Can you help me, please ?

**Comment by alexeyvasilyev** [comment]
Because this is MJPEG stream. Library supports only H.264 stream at the moment.

**Comment by quockhanh1198** [comment]
Thanks for your reply, I will fix this issue.
