### ISSUE TITLE
Support for the popular H.265 RTSP streams?

### ISSUE THREAD

**Issue by ingura** [alexeyvasilyev/rtsp-client-android#55]
Is there an easy way to decode and display a H.265 stream using this library?

**Comment by alexeyvasilyev** [comment]
Not yet. H265 support in TODO list.

**Comment by ingura** [comment]
That's great! I am glad the project is not dead.

You must be pretty busy given all the mad changes around Europe. I noticed that H.265 was in your planed TODO for more than a year. 
What would be the time-frame in which you hope to do it?

**Comment by NicolasGodfather** [comment]
Hi Alexei! Thanks for your library! I'm using it in my project, but for me the most important thing is that it supports h265 codec. I hope you will support it soon.

**Comment by alexeyvasilyev** [comment]
Done. Check version 5.0.0.
