### ISSUE TITLE
Using Mobile Data Connection Reset ()

### ISSUE THREAD

**Issue by Praveen-Sundriyal** [alexeyvasilyev/rtsp-client-android#71]
i am using this library when i connect through my wifi i can stream the video 
but if i change the network into mobile data or another wifi or hotspot 
i got nothing sometime connection reset 
sometime socket connection time out 
or sometime status show connected but stream is not available 
is there something i miss 
Please help

**Comment by alexeyvasilyev** [comment]
You need to setup port forwarding on your router to allow accessing RTSP stream from another network.
