### ISSUE TITLE
is there a listener to capture a decoded frame?

### ISSUE THREAD

**Issue by yxdragon** [alexeyvasilyev/rtsp-client-android#76]
I whant to snapshot a frame, and do some image analysis. I saw onRtspVideoNalUnitReceived can take the initial frame, but how can I get a decoded frame's rgb bytes?.

**Comment by alexeyvasilyev** [comment]
The best way is to use `[RtspImageView](https://github.com/alexeyvasilyev/rtsp-client-android/blob/master/library-client-rtsp/src/main/java/com/alexvas/rtsp/widget/RtspImageView.kt)`. Assign `onRtspImageBitmapListener` to get RGB bitmaps.
