### ISSUE TITLE
Image processing after decoding and before rendering on screen

### ISSUE THREAD

**Issue by nilsvanrompaey** [alexeyvasilyev/rtsp-client-android#79]
Hi there,

First of all, thank you for making this app. For my project, I would like to process the streamed frames before rendering them on the screen.  The image processing function consists of some fairly simple OpenCV operations performed on the bitmap of each decoded frame.

I'm new to Java and Kotlin and to RTSP, so would you mind giving some pointers as to what kind of changes to the code are necessary to achieve this? Where can the decoded images be exposed so they can be processed and then rendered afterwards?

Thanks in advance!

**Comment by alexeyvasilyev** [comment]
The easiest way to get bitmap from SurfaceView is to use [PixelCopy](https://developer.android.com/reference/android/view/PixelCopy) API

```
val thread = HandlerThread("PixelCopyHelper")
val handler = Handler(thread.looper)
val surfaceBitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
val pixelCopyListener = PixelCopy.OnPixelCopyFinishedListener { copyResult ->
            when (copyResult) {
                PixelCopy.SUCCESS -> {  Log.i(TAG, "surfaceBitmap contains new bitmap" }
                else -> { Log.e(TAG, "PixelCopy failed" }
           }
}
PixelCopy.request(surface, surfaceBitmap, pixelCopyListener, handler)
```

But don't expect good performance of that solution.

**Comment by nilsvanrompaey** [comment]
Thank you for your quick response. 
The application is supposed to work in real-time. so latency is crucial. How bad do you think PixelCopy would be with respect to latency?
Is there any other solution that might be more performant? E.g. would it be feasible to insert another thread that handles the processing before the images are rendered?

**Comment by alexeyvasilyev** [comment]
On Pixel 8 Pro with 1440p @ 20 fps video stream, I can get 12 fps only via PixelCopy.
But you should try on your own.
