### ISSUE TITLE
Switch two camera

### ISSUE THREAD

**Issue by DongPhamBK** [alexeyvasilyev/rtsp-client-android#84]
I need to switch between 2 rtsp links on the same RtspSurfaceView. When I do this (refer to the code below). But the video is wrong and seems to show a combination of images between the 2 rtsp links. Can you suggest any ideas, thanks!

Ex: 
 fun switchCamera(url: String){
            if (binding.svVideo.isStarted()) {
                binding.svVideo.stop()
            }
            
            val uri = Uri.parse(url)
            binding.svVideo.apply {
                init(uri, liveViewModel.rtspUsername.value, liveViewModel.rtspPassword.value, "rtsp-client-android")
                debug = true
                start(true, true)
            }
        }

**Comment by alexeyvasilyev** [comment]
So, your start `RtspSurfaceView` with `url1`, then stop it, assign `url2` and start it again. Am I right?

**Comment by DongPhamBK** [comment]
I tried delaying a bit before switching between the 2 urls, and it worked, maybe the problem is with my device, it's quite weak. Thank you for your feedback.
