### ISSUE TITLE
RtspStatusListener not work with wrong rtsp link

### ISSUE THREAD

**Issue by DongPhamBK** [alexeyvasilyev/rtsp-client-android#86]
When I use a wrong rtsp link (ex: rtsp://abcd), RtspStatusListener seems to not work. But in previous version it still works. I need to handle RtspStatusListener to return message to user in case they enter wrong rtsp link. Can you help me? Thanks!

**Comment by alexeyvasilyev** [comment]
Please attach the log regarding this issue.

**Comment by alexeyvasilyev** [comment]
Try 5.1.1.
It will report onRtspStatusFailed() when host or port is invalid

**Comment by DongPhamBK** [comment]
It worked. Thank you for your support!
