### ISSUE TITLE
java.lang.NullPointerException。androidx.camera:camera-core:1.4.0-rc03

### ISSUE THREAD

**Issue by 9276** [alexeyvasilyev/rtsp-client-android#87]
Compilation failed to complete, origin: C:\Users\Administrator\.gradle\caches\transforms-3\bf9f0408c91c67684d3630cbaa5dfebd\transformed\camera-core-1.4.0-rc03-runtime.jar:androidx/camera/core/CameraState$ErrorType.class

How should we solve it

**Comment by alexeyvasilyev** [comment]
This is your side issue.
1. Install latest stable Android studio
2. Invalid caches (File - Invalidate Caches...)
3. Try to change `androidx.camera:camera-core:1.4.0-rc03` to `androidx.camera:camera-core:1.4.0-rc02` in build.gradle
