### ISSUE TITLE
RtspDataListener callback failed

### ISSUE THREAD

**Issue by FaceAI2025** [alexeyvasilyev/rtsp-client-android#94]
Successful run demo on Android  Device , but 

RtspDataListener,onRtspDataApplicationDataReceived never call back;

```
    private val rtspDataListener = object: RtspDataListener {
        override fun onRtspDataApplicationDataReceived(data: ByteArray, offset: Int, length: Int, timestamp: Long) {
                // nerver call back
        }
    }
```

we need call back data for real time AI analysis, what the best way? thank you.

**Comment by alexeyvasilyev** [comment]
onRtspDataApplicationDataReceived() is called only for RTSP devices which support application data. Usually there is a metadata being sent. Majority of RTSP cameras do not support it.

If you want image processing, you need to use [RtspImageView](https://github.com/alexeyvasilyev/rtsp-client-android/blob/master/library-client-rtsp/src/main/java/com/alexvas/rtsp/widget/RtspImageView.kt) class which allows obtaining bitmap data.

**Comment by FaceAI2025** [comment]
```       
 binding.ivVideoImage.setOnRtspImageBitmapListener(new RtspImageView.RtspImageBitmapListener() {
            @Override
            public void onRtspImageBitmapObtained(@NonNull Bitmap bitmap) {

               // Log   Thread.currentThread.getName() == Main
                FaceSearchEngine.Companion.getInstance().runSearch(bitmap);
            }
        });
```

onRtspImageBitmapObtained call back run on Main Thread , can we dispose this like Android camerax analysis call bak

![image](https://github.com/user-attachments/assets/455a936e-2258-4258-a8b1-704a808a29b1)


Thank you @alexeyvasilyev

**Comment by FaceAI2025** [comment]
singleThreadExecutor.execute(()->{
                Log.d("RTSP","Thread Name: "+Thread.currentThread().getName());
                FaceSearchEngine.Companion.getInstance().runSearch(bitmap);
            });


I can dispose it myself, thank you
