### ISSUE TITLE
Zooming

### ISSUE THREAD

**Issue by shervinkoushan** [alexeyvasilyev/rtsp-client-android#96]
Hi,
Thanks for creating this great library!
Would you consider adding support for zooming in on the `RtspSurfaceView`?

**Comment by alexeyvasilyev** [comment]
You can use any 3d party library which support surface view zoom, e.g. https://github.com/natario1/ZoomLayout

**Comment by shervinkoushan** [comment]
> You can use any 3d party library which support surface view zoom, e.g. https://github.com/natario1/ZoomLayout

I'll check that out, thanks for the quick answer!
